(eval-when-compile    (require 'color-theme))
(defun color-theme-active ()
  "Color theme Active inspired by jEdit theme of the same name emacsified by Scott Jaderholm."
  (interactive)
  (color-theme-install
   '(color-theme-active
     ((background-color . "SystemWindow")
      (background-mode . light)
      (border-color . "black")
      (cursor-color . "black")
      (foreground-color . "SystemWindowText")
      (mouse-color . "black"))
     ((Man-overstrike-face . bold)
      (Man-reverse-face . highlight)
      (Man-underline-face . underline)
      (apropos-keybinding-face . underline)
      (apropos-label-face italic variable-pitch)
      (apropos-match-face . match)
      (apropos-property-face . bold-italic)
      (apropos-symbol-face . bold)
      (compilation-message-face . underline)
      (diary-face . diary)
      (highline-face . highline-face)
      (highline-vertical-face . highline-vertical-face)
      (list-matching-lines-buffer-name-face . underline)
      (list-matching-lines-face . match)
      (org-goto-interface . outline)
      (org-remember-interactive-interface . refile)
      (tags-tag-face . default)
      (view-highlight-face . highlight)
      (widget-mouse-face . highlight))
     (default ((t (:stipple nil :background "SystemWindow" :foreground "SystemWindowText" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "outline" :family "Terminus"))))
     (anything-bookmarks-su-face ((t (:foreground "red"))))
     (anything-dir-heading ((t (:background "Pink" :foreground "Blue"))))
     (anything-dir-priv ((t (:background "LightGray" :foreground "DarkRed"))))
     (anything-file-name ((t (:foreground "Blue"))))
     (anything-gentoo-match-face ((t (:foreground "red"))))
     (anything-header ((t (:foreground "grey20" :background "grey90" :box (:line-width -1 :style released-button)))))
     (anything-isearch-match ((t (:background "Yellow"))))
     (anything-overlay-line-face ((t (:background "IndianRed4" :underline t))))
     (anything-visible-mark ((t (:background "green1"))))
     (anything-w3m-bookmarks-face ((t (:foreground "cyan1" :underline t))))
     (bold ((t (:bold t :weight bold))))
     (bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
     (border ((t (nil))))
     (buffer-menu-buffer ((t (:bold t :weight bold))))
     (button ((t (:underline t))))
     (calendar-today ((t (:underline t))))
     (comint-highlight-input ((t (:bold t :weight bold))))
     (comint-highlight-prompt ((t (:foreground "dark blue"))))
     (compilation-column-number ((t (:foreground "ForestGreen"))))
     (compilation-error ((t (:bold t :weight bold :foreground "Red1"))))
     (compilation-info ((t (:bold t :foreground "Green3" :weight bold))))
     (compilation-line-number ((t (:bold t :weight bold :foreground "#006699"))))
     (compilation-warning ((t (:bold t :foreground "Orange" :weight bold))))
     (completions-common-part ((t (:family "Terminus" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "SystemWindowText" :background "SystemWindow" :stipple nil :height 120))))
     (completions-first-difference ((t (:bold t :weight bold))))
     (csv-separator-face ((t (:foreground "red"))))
     (cursor ((t (nil))))
     (diary ((t (:foreground "red1"))))
     (diary-anniversary ((t (:bold t :weight bold :foreground "#cc3300"))))
     (diary-button ((t (nil))))
     (diary-time ((t (:bold t :weight bold :foreground "#006699"))))
     (dired-directory ((t (:bold t :weight bold :foreground "#006699"))))
     (dired-flagged ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-header ((t (:foreground "ForestGreen"))))
     (dired-ignored ((t (:foreground "grey50"))))
     (dired-mark ((t (:bold t :weight bold :foreground "#660066"))))
     (dired-marked ((t (:bold t :weight bold :foreground "Red1"))))
     (dired-perm-write ((t (:family "Terminus" :foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "SystemWindowText" :background "SystemWindow" :stipple nil :height 120))))
     (dired-symlink ((t (:bold t :weight bold :foreground "#cc3300"))))
     (dired-warning ((t (:bold t :weight bold :foreground "Red1"))))
     (ediff-current-diff-A ((t (:background "pale green" :foreground "firebrick"))))
     (ediff-current-diff-Ancestor ((t (:background "VioletRed" :foreground "Black"))))
     (ediff-current-diff-B ((t (:background "Yellow" :foreground "DarkOrchid"))))
     (ediff-current-diff-C ((t (:background "Pink" :foreground "Navy"))))
     (ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
     (ediff-even-diff-Ancestor ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-B ((t (:background "Grey" :foreground "White"))))
     (ediff-even-diff-C ((t (:background "light grey" :foreground "Black"))))
     (ediff-fine-diff-A ((t (:background "sky blue" :foreground "Navy"))))
     (ediff-fine-diff-Ancestor ((t (:background "Green" :foreground "Black"))))
     (ediff-fine-diff-B ((t (:background "cyan" :foreground "Black"))))
     (ediff-fine-diff-C ((t (:background "Turquoise" :foreground "Black"))))
     (ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
     (ediff-odd-diff-Ancestor ((t (:background "gray40" :foreground "cyan3"))))
     (ediff-odd-diff-B ((t (:background "light grey" :foreground "Black"))))
     (ediff-odd-diff-C ((t (:background "Grey" :foreground "White"))))
     (egg-an-tag-mono ((t (:bold t :weight bold :foreground "DarkGoldenRod"))))
     (egg-blame ((t (:foreground "black"))))
     (egg-blame-culprit ((t (:family "Sans Serif" :background "grey85" :foreground "grey35" :height 1.1))))
     (egg-blame-subject ((t (:background "grey85" :family "Sans Serif" :foreground "black" :height 1.1))))
     (egg-branch ((t (:bold t :weight bold :family "Sans Serif" :foreground "SkyBlue" :height 1.2100000000000002))))
     (egg-branch-mono ((t (:bold t :weight bold :foreground "SkyBlue"))))
     (egg-diff-add ((t (:foreground "blue1"))))
     (egg-diff-conflict ((t (:foreground "Blue"))))
     (egg-diff-del ((t (:foreground "red"))))
     (egg-diff-file-header ((t (:bold t :weight bold :family "Sans Serif" :foreground "SlateBlue" :height 1.1))))
     (egg-diff-hunk-header ((t (:background "grey85"))))
     (egg-diff-none ((t (:foreground "grey50"))))
     (egg-electrict-choice ((t (:bold t :family "Sans Serif" :foreground "Blue" :weight bold))))
     (egg-graph ((t (:foreground "grey90"))))
     (egg-header ((t (:bold t :family "Sans Serif" :weight bold :height 1.1))))
     (egg-help-header-1 ((t (:bold t :foreground "navy" :family "Sans Serif" :weight bold))))
     (egg-help-header-2 ((t (:family "Sans Serif" :foreground "Black" :height 0.9))))
     (egg-help-key ((t (:bold t :foreground "SkyBlue" :weight bold :height 0.9))))
     (egg-log-HEAD ((t (:background "darkseagreen2"))))
     (egg-log-buffer-mark ((t (:bold t :weight bold :foreground "black"))))
     (egg-remote-mono ((t (:bold t :weight bold :foreground "Orchid"))))
     (egg-section-title ((t (:bold t :weight bold :family "Sans Serif" :foreground "DarkGoldenrod" :height 1.2100000000000002))))
     (egg-stash-mono ((t (:bold t :weight bold :foreground "DarkGoldenRod"))))
     (egg-tag-mono ((t (:bold t :weight bold :foreground "GoldenRod"))))
     (egg-term ((t (:bold t :weight bold :foreground "SkyBlue"))))
     (egg-text-1 ((t (:foreground "navy" :family "Sans Serif"))))
     (egg-text-2 ((t (:foreground "navy" :family "Sans Serif" :height 1.1))))
     (egg-text-3 ((t (:foreground "navy" :family "Sans Serif" :height 1.2))))
     (egg-text-4 ((t (:foreground "navy" :family "Sans Serif" :height 1.4))))
     (egg-text-base ((t (:family "Sans Serif" :foreground "navy"))))
     (egg-text-help ((t (:foreground "navy" :family "Sans Serif" :height 0.8))))
     (egg-unmerged-diff-file-header ((t (:bold t :family "Sans Serif" :weight bold :foreground "Red" :height 1.1))))
     (egg-warning ((t (:bold t :weight bold :foreground "Red"))))
     (emms-playlist-selected-face ((t (:background "blue3" :foreground "white"))))
     (emms-playlist-track-face ((t (:foreground "Blue"))))
     (epa-field-body ((t (:italic t :slant italic))))
     (epa-field-name ((t (:bold t :weight bold))))
     (epa-mark ((t (:bold t :foreground "red" :weight bold))))
     (epa-string ((t (:foreground "blue4"))))
     (epa-validity-disabled ((t (:italic t :slant italic))))
     (epa-validity-high ((t (:bold t :weight bold))))
     (epa-validity-low ((t (:italic t :slant italic))))
     (epa-validity-medium ((t (:italic t :slant italic))))
     (escape-glyph ((t (:foreground "brown"))))
     (esk-clojure-trace-face ((t (:foreground "grey55"))))
     (ffap ((t (:background "darkseagreen2"))))
     (file-name-shadow ((t (:foreground "grey50"))))
     (find-file-root-header-face ((t (:background "red3" :foreground "white"))))
     (fixed-pitch ((t (:family "Monospace"))))
     (font-lock-builtin-face ((t (nil))))
     (font-lock-comment-delimiter-face ((t (:italic t :slant italic :foreground "#009933"))))
     (font-lock-comment-face ((t (:italic t :foreground "#009933" :slant italic))))
     (font-lock-constant-face ((t (:bold t :foreground "#660066" :weight bold))))
     (font-lock-doc-face ((t (:foreground "#990099"))))
     (font-lock-function-name-face ((t (:bold t :foreground "#006699" :weight bold))))
     (font-lock-keyword-face ((t (:bold t :foreground "#cc3300" :weight bold))))
     (font-lock-negation-char-face ((t (nil))))
     (font-lock-preprocessor-face ((t (nil))))
     (font-lock-regexp-grouping-backslash ((t (:bold t :weight bold))))
     (font-lock-regexp-grouping-construct ((t (:bold t :weight bold))))
     (font-lock-string-face ((t (:foreground "#990099"))))
     (font-lock-type-face ((t (:foreground "ForestGreen"))))
     (font-lock-variable-name-face ((t (:bold t :foreground "#006699" :weight bold))))
     (font-lock-warning-face ((t (:bold t :foreground "Red1" :weight bold))))
     (fringe ((t (:background "grey95" :foreground "#8080ff"))))
     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey90" :foreground "grey20" :box nil))))
     (help-argument-name ((t (nil))))
     (highlight ((t (:background "darkseagreen2"))))
     (highline-face ((t (:background "#e5f9ff"))))
     (highline-vertical-face ((t (:background "lightcyan"))))
     (holiday ((t (:background "pink"))))
     (ido-first-match ((t (:bold t :weight bold))))
     (ido-incomplete-regexp ((t (:bold t :weight bold :foreground "Red1"))))
     (ido-indicator ((t (:background "red1" :foreground "yellow1" :width condensed))))
     (ido-only-match ((t (:foreground "ForestGreen"))))
     (ido-subdir ((t (:bold t :foreground "blue" :weight bold))))
     (isearch ((t (:background "magenta3" :foreground "lightskyblue1"))))
     (isearch-fail ((t (:background "RosyBrown1"))))
     (italic ((t (:underline t))))
     (lazy-highlight ((t (:background "paleturquoise"))))
     (link ((t (:foreground "blue1" :underline t))))
     (link-visited ((t (:underline t :foreground "magenta4"))))
     (match ((t (:background "yellow1"))))
     (menu ((t (:foreground "systemmenu" :background "systemmenutext"))))
     (minibuffer-noticeable-prompt ((t (:foreground "medium blue"))))
     (minibuffer-prompt ((t (:foreground "medium blue"))))
     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (mode-line-buffer-id ((t (:bold t :weight bold))))
     (mode-line-emphasis ((t (:bold t :weight bold))))
     (mode-line-highlight ((t (:box (:line-width 2 :color "grey40" :style released-button)))))
     (mode-line-inactive ((t (:background "grey90" :foreground "grey20" :box (:line-width -1 :color "grey75" :style nil) :weight light))))
     (mouse ((t (nil))))
     (mpg123-face-cur ((t (:background "#004080" :foreground "yellow"))))
     (mpg123-face-indicator ((t (:background "#7f3000" :foreground "yellow"))))
     (mpg123-face-slider ((t (:background "yellow" :foreground "black"))))
     (next-error ((t (:background "darkseagreen2"))))
     (nobreak-space ((t (:foreground "brown" :underline t))))
     (org-agenda-column-dateline ((t (:family "Terminus" :weight normal :slant normal :underline nil :strike-through nil :background "grey90" :height 120))))
     (org-agenda-date ((t (:foreground "Blue1"))))
     (org-agenda-date-today ((t (:italic t :bold t :foreground "Blue1" :slant italic :weight bold))))
     (org-agenda-date-weekend ((t (:bold t :foreground "Blue1" :weight bold))))
     (org-agenda-dimmed-todo-face ((t (:foreground "grey50"))))
     (org-agenda-done ((t (:foreground "ForestGreen"))))
     (org-agenda-restriction-lock ((t (:background "yellow1"))))
     (org-agenda-structure ((t (:foreground "Blue1"))))
     (org-archived ((t (:foreground "grey50"))))
     (org-block ((t (:foreground "grey50"))))
     (org-checkbox ((t (:bold t :weight bold))))
     (org-clock-overlay ((t (:background "yellow1"))))
     (org-code ((t (:foreground "grey50"))))
     (org-column ((t (:background "grey90" :strike-through nil :underline nil :slant normal :weight normal :height 120 :family "Terminus"))))
     (org-column-title ((t (:bold t :background "grey90" :underline t :weight bold))))
     (org-date ((t (:foreground "Purple" :underline t))))
     (org-done ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-drawer ((t (:foreground "Blue1"))))
     (org-ellipsis ((t (:foreground "DarkGoldenrod" :underline t))))
     (org-footnote ((t (:foreground "Purple" :underline t))))
     (org-formula ((t (:foreground "Firebrick"))))
     (org-headline-done ((t (:foreground "RosyBrown"))))
     (org-hide ((t (:foreground "white"))))
     (org-latex-and-export-specials ((t (:foreground "SaddleBrown"))))
     (org-level-1 ((t (:bold t :weight bold))))
     (org-level-2 ((t (:bold t :foreground "#006699" :weight bold))))
     (org-level-3 ((t (:bold t :foreground "#cc3300" :weight bold))))
     (org-level-4 ((t (:italic t :bold t :foreground "#009933" :slant italic :weight bold))))
     (org-level-5 ((t (:bold t :foreground "#660066" :weight bold))))
     (org-level-6 ((t (:bold t :foreground "ForestGreen" :weight bold))))
     (org-level-7 ((t (nil))))
     (org-level-8 ((t (:foreground "#990099"))))
     (org-link ((t (:foreground "Purple" :underline t))))
     (org-meta-line ((t (:italic t :slant italic :foreground "#009933"))))
     (org-mode-line-clock ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
     (org-property-value ((t (nil))))
     (org-scheduled ((t (:foreground "DarkGreen"))))
     (org-scheduled-previously ((t (:foreground "Firebrick"))))
     (org-scheduled-today ((t (:foreground "DarkGreen"))))
     (org-sexp-date ((t (:foreground "Purple"))))
     (org-special-keyword ((t (:foreground "RosyBrown"))))
     (org-table ((t (:foreground "Blue1"))))
     (org-tag ((t (:bold t :weight bold))))
     (org-target ((t (:underline t))))
     (org-time-grid ((t (:foreground "DarkGoldenrod"))))
     (org-todo ((t (:bold t :foreground "Red1" :weight bold))))
     (org-upcoming-deadline ((t (:foreground "Firebrick"))))
     (org-verbatim ((t (:foreground "grey50"))))
     (org-warning ((t (:bold t :weight bold :foreground "Red1"))))
     (outline-1 ((t (:bold t :weight bold :foreground "#006699"))))
     (outline-2 ((t (:bold t :weight bold :foreground "#006699"))))
     (outline-3 ((t (:bold t :weight bold :foreground "#cc3300"))))
     (outline-4 ((t (:italic t :slant italic :foreground "#009933"))))
     (outline-5 ((t (:foreground "ForestGreen"))))
     (outline-6 ((t (:bold t :weight bold :foreground "#660066"))))
     (outline-7 ((t (nil))))
     (outline-8 ((t (:foreground "#990099"))))
     (query-replace ((t (:foreground "lightskyblue1" :background "magenta3"))))
     (region ((t (:background "darkseagreen2"))))
     (scroll-bar ((t (:foreground "systemscrollbar"))))
     (secondary-selection ((t (:background "yellow1"))))
     (shadow ((t (:foreground "grey50"))))
     (show-paren-match ((t (:background "turquoise"))))
     (show-paren-mismatch ((t (:background "purple" :foreground "white"))))
     (sldb-catch-tag-face ((t (nil))))
     (sldb-condition-face ((t (nil))))
     (sldb-detailed-frame-line-face ((t (nil))))
     (sldb-frame-label-face ((t (nil))))
     (sldb-frame-line-face ((t (nil))))
     (sldb-local-name-face ((t (nil))))
     (sldb-local-value-face ((t (nil))))
     (sldb-non-restartable-frame-line-face ((t (nil))))
     (sldb-reference-face ((t (:underline t))))
     (sldb-restart-face ((t (nil))))
     (sldb-restart-number-face ((t (:bold t :weight bold))))
     (sldb-restart-type-face ((t (:bold t :weight bold :foreground "#cc3300"))))
     (sldb-restartable-frame-line-face ((t (:foreground "lime green"))))
     (sldb-section-face ((t (nil))))
     (sldb-topline-face ((t (nil))))
     (slime-error-face ((t (:underline "red"))))
     (slime-highlight-edits-face ((t (:background "lightgray"))))
     (slime-highlight-face ((t (:background "darkseagreen2" :underline nil))))
     (slime-inspector-action-face ((t (:bold t :weight bold :foreground "Red1"))))
     (slime-inspector-label-face ((t (:bold t :weight bold :foreground "#660066"))))
     (slime-inspector-topline-face ((t (nil))))
     (slime-inspector-type-face ((t (:foreground "ForestGreen"))))
     (slime-inspector-value-face ((t (nil))))
     (slime-note-face ((t (:underline "brown4"))))
     (slime-reader-conditional-face ((t (:italic t :slant italic :foreground "#009933"))))
     (slime-repl-input-face ((t (:bold t :weight bold))))
     (slime-repl-inputed-output-face ((t (:foreground "Red"))))
     (slime-repl-output-face ((t (:foreground "#990099"))))
     (slime-repl-output-mouseover-face ((t (:foreground "Red" :box (:line-width 1 :color "black" :style released-button)))))
     (slime-repl-prompt-face ((t (:bold t :weight bold :foreground "#cc3300"))))
     (slime-repl-result-face ((t (nil))))
     (slime-style-warning-face ((t (:underline "brown"))))
     (slime-warning-face ((t (:underline "orange"))))
     (speedbar-button-face ((t (:foreground "green4"))))
     (speedbar-directory-face ((t (:foreground "blue4"))))
     (speedbar-file-face ((t (:foreground "cyan4"))))
     (speedbar-highlight-face ((t (:background "green"))))
     (speedbar-selected-face ((t (:foreground "red" :underline t))))
     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
     (speedbar-tag-face ((t (:foreground "brown"))))
     (tmm-inactive ((t (:foreground "grey50"))))
     (tool-bar ((t (:background "systembuttonface" :foreground "systembuttontext" :box (:line-width 1 :style released-button)))))
     (tooltip ((t (:family "Sans Serif" :background "systeminfowindow" :foreground "systeminfotext"))))
     (trailing-whitespace ((t (:background "red1"))))
     (underline ((t (:underline t))))
     (variable-pitch ((t (:family "Sans Serif"))))
     (vertical-border ((t (nil))))
     (widget-button ((t (:bold t :weight bold))))
     (widget-button-pressed ((t (:foreground "red1"))))
     (widget-documentation ((t (:foreground "dark green"))))
     (widget-field ((t (:background "gray85"))))
     (widget-inactive ((t (:foreground "grey50"))))
     (widget-single-line-field ((t (:background "gray85"))))
     (woman-addition ((t (:foreground "orange"))))
     (woman-bold ((t (:bold t :foreground "blue1" :weight bold))))
     (woman-italic ((t (:italic t :foreground "red1" :underline t :slant italic))))
     (woman-symbol ((t (nil))))
     (woman-unknown ((t (:foreground "brown")))))))
(add-to-list 'color-themes '(color-theme-active  "Active" "Scott Jaderholm"))