[colors.bright]
black = "0x90a4ae"
red = "0xe53935"
green = "0x91b859"
yellow = "0xf6a434"
blue = "0x6182b8"
magenta = "0x7c4dff"
cyan = "0x39adb5"
white = "0xffffff"

[colors.cursor]
text = "0x000000"
cursor = "0xf6a434"

[colors.normal]
black = "0x000000"
red = "0xe53935"
green = "0x91b859"
yellow = "0xf6a434"
blue = "0x6182b8"
magenta = "0x7c4dff"
cyan = "0x39adb5"
white = "0xffffff"

[colors.primary]
background = "0xfafafa"
foreground = "0x546e7a"
