#!/bin/sh
#
# An example hook script to prepare a packed repository for use over
# dumb transports.
#
# To enable this hook, rename this file to "post-update".

chmod 600 $HOME/.etc/mail/msmtprc

# exec git update-server-info
