#!/bin/sh

m_goobook_query()
{
    goobook query "$@" \
    | awk 'BEGIN {
               FS = "\t"
               OFS = "\t"
               getline # skip first header line
           }
           {
               print tolower($1), $2, $3
           }
           '
}
