#!/bin/sh

m_mu_query()
{
    mu cfind --muhome="$XDG_CACHE_HOME/mu-sent-index" --format=mutt-ab "$@" 2>/dev/null \
    | awk 'BEGIN {
               FS = "\t"
               OFS = "\t"
               getline # skip first header line
           }
           /^[^\t]+\t[^\t]+\t$/ {
               print tolower($1), $2, "mu"
           }
           /^[^\t]+\t\t$/ {
               print tolower($1), tolower($1), "mu"
           }
           '
}
