#!/bin/sh
# The shebang is just to get shellcheck to use POSIX rules
# shellcheck disable=SC3043
#
# https://github.com/grawity/dotfiles/blob/master/.environ.notes
#
# *** {{@@ header() @@}} ***

# shellcheck disable=SC1009
ismac() {
    # shellcheck disable=SC1073,SC1054,SC1083
    {{@@ "true" if os.lower() == "darwin" else "false" @@}}
}

# This wrapper makes the filename of the sourced file available as $1 in the file
_source() {
    # shellcheck source=/dev/null
    . "$1"
}

if [ -f ~/.local/etc/profile ]; then
    _source ~/.local/etc/profile
fi
if [ -d ~/.local/etc/profile.d ]; then
    for file in "$HOME"/.local/etc/profile.d/??_*; do
        # Protect against empty directories
        [ -e "$file" ] || continue
        _source "$file"
    done
fi


export XDG_DATA_HOME="$HOME/.local/share"
# export XDG_DATA_DIRS=/usr/local/share/:/usr/share/
export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_CONFIG_DIRS=/etc/xdg
export XDG_STATE_HOME="$HOME/.local/state"
if ismac; then
    export XDG_CACHE_HOME="$HOME/Library/Caches"
else
    export XDG_CACHE_HOME="$HOME/.cache"
fi
if ismac; then
    export XDG_RUNTIME_DIR="$TMPDIR"
fi

export DOTFILES="{{@@ _dotdrop_dotpath @@}}"
export DOTDROP_CONFIG="{{@@ _dotdrop_cfgpath @@}}"
export DOTDROP_PROFILE=default

if [ -n "$HOMEBREW_PREFIX" ]; then
    PATH="$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$PATH"
    PATH="$HOMEBREW_PREFIX/opt/gnu-getopt/bin:$PATH"
    PATH="$HOMEBREW_PREFIX/opt/gawk/libexec/gnubin:$PATH"
    PATH="$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$PATH"
    PATH="$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin:$PATH"
fi

# Necessary for fd-find on Debian
PATH="/usr/lib/cargo/bin:$PATH"

PATH="$PATH:/usr/local/sbin"
PATH="$PATH:/sbin"
PATH="$PATH:/usr/sbin"
PATH="$PATH:/usr/local/games"
PATH="$PATH:/usr/games"

export LD_LIBRARY_PATH="$HOME/.local/lib/ld"


# Use sensible date formats
if locale -a | command grep -q en_DK.UTF-8; then
    export LC_TIME=en_DK.UTF-8
fi

export EDITOR=nvim
export VISUAL="$EDITOR"
export BROWSER=xdg-open

export GOPATH="$HOME/src/go"
PATH="$GOPATH/bin:$PATH"

# export WINEPREFIX="$XDG_DATA_HOME"/wine/prefixes/default

export RUSTUP_HOME="$HOME/.var/lib/rustup"
export CARGO_HOME="$HOME/.var/lib/cargo"
PATH="$CARGO_HOME/bin:$PATH"
if command -v sccache > /dev/null; then
    export RUSTC_WRAPPER=sccache
fi

export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/pycache"

export LUA_INIT="@$DOTFILES/lua/init.lua"
export LUAROCKS_CONFIG="$DOTFILES/lua/luarocks-config.lua"
if command -v luarocks > /dev/null; then
    PATH="$(luarocks config deploy_bin_dir):$PATH"
fi

export CCACHE_DIR="$XDG_CACHE_HOME/ccache"
export CCACHE_COMPRESS=1
export CCACHE_HASHDIR=1

export GITHUB_USER=majutsushi

export DVDCSS_CACHE="$XDG_CACHE_HOME/dvdcss"
export GTK_OVERLAY_SCROLLING=0
export NO_AT_BRIDGE=1
export GRAMPSHOME="$XDG_DATA_HOME"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

export IDEA_PROPERTIES="$DOTFILES/idea/idea.properties"
export IDEA_VM_OPTIONS="$DOTFILES/idea/idea64.vmoptions"

# https://cran.r-project.org/web/packages/startup/vignettes/startup-intro.html
export R_PROFILE_USER="$DOTFILES/R/Rprofile"


# Make sure these are first in PATH
PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/usr/bin:$PATH"
PATH="$HOME/.bin:$PATH"
PATH="$HOME/bin:$PATH"

unset -f _source

# shellcheck disable=SC1072
# vim: ft=sh
