#!/bin/sh
# The shebang is just to get shellcheck to use POSIX rules
# shellcheck disable=SC3043
#
# https://github.com/grawity/dotfiles/blob/master/.environ.notes
#
# *** {{@@ header() @@}} ***

# shellcheck disable=SC1009
ismac() {
    # shellcheck disable=SC1073,SC1054,SC1083
    {{@@ "true" if os == "Darwin" else "false" @@}}
}

_add_to_path() {
    # This is non-POSIX but works in dash
    local pos="$1"
    local pathvar="$2"
    local dir="$3"

    case "$(eval "echo \"\$$pathvar\"")" in
        $dir:*|*:$dir:*|*:$dir)
            # Don't add again
            ;;
        *)
            case $pos in
                pre)
                    eval "$pathvar='$dir':\$$pathvar" ;;
                post)
                    eval "$pathvar=\$$pathvar:'$dir'" ;;
            esac
            ;;
    esac
}


# This wrapper makes the filename of the sourced file available as $1 in the file
_source() {
    # shellcheck source=/dev/null
    . "$1"
}

if [ -f ~/.local/etc/profile ]; then
    _source ~/.local/etc/profile
fi
if [ -d ~/.local/etc/profile.d ]; then
    for file in "$HOME"/.local/etc/profile.d/??_*; do
        # Protect against empty directories
        [ -e "$file" ] || continue
        _source "$file"
    done
fi


export XDG_DATA_HOME="$HOME/.local/share"
# export XDG_DATA_DIRS=/usr/local/share/:/usr/share/
export XDG_CONFIG_HOME="$HOME/.config"
# export XDG_CONFIG_DIRS=/etc/xdg
export XDG_STATE_HOME="$HOME/.local/state"
if ismac; then
    export XDG_CACHE_HOME="$HOME/Library/Caches"
else
    export XDG_CACHE_HOME="$HOME/.cache"
fi
if ismac; then
    export XDG_RUNTIME_DIR="$TMPDIR"
fi

export DOTFILES="{{@@ _dotdrop_dotpath @@}}"
export DOTDROP_CONFIG="{{@@ _dotdrop_cfgpath @@}}"
export DOTDROP_PROFILE=default

export PYENV_ROOT="$XDG_DATA_HOME/pyenv"
if [ -d "$PYENV_ROOT/bin" ]; then
    _add_to_path pre PATH "$PYENV_ROOT/bin"
fi
if command -v pyenv > /dev/null; then
    eval "$(pyenv init --path)"
fi

if [ -n "$HOMEBREW_PREFIX" ]; then
    _add_to_path pre PATH "$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin"
    _add_to_path pre PATH "$HOMEBREW_PREFIX/opt/gnu-getopt/bin"
    _add_to_path pre PATH "$HOMEBREW_PREFIX/opt/gawk/libexec/gnubin"
    _add_to_path pre PATH "$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin"
    _add_to_path pre PATH "$HOMEBREW_PREFIX/opt/gnu-tar/libexec/gnubin"
fi

# Necessary for fd-find on Debian
_add_to_path pre PATH "/usr/lib/cargo/bin"

_add_to_path pre PATH "$HOME/.local/bin"
_add_to_path pre PATH "$HOME/usr/bin"
_add_to_path pre PATH "$HOME/.bin"

_add_to_path post PATH /usr/local/sbin
_add_to_path post PATH /sbin
_add_to_path post PATH /usr/sbin

if [ -z "$MANPATH" ]; then
    MANPATH="$(manpath)"
fi
export MANPATH

export LD_LIBRARY_PATH="$HOME/.local/lib/ld"


# Make sure Monday is the first day of the week, as it should be.
if locale -a | command grep -q en_GB.UTF-8; then
    export LC_TIME=en_GB.UTF-8
fi

export EDITOR=nvim
export VISUAL="$EDITOR"
export BROWSER=xdg-open

export GOPATH="$HOME/src/go"
_add_to_path post PATH "$GOPATH/bin"

# export WINEPREFIX="$XDG_DATA_HOME"/wine/prefixes/default

export RUSTUP_HOME="$HOME/.var/lib/rustup"
export CARGO_HOME="$HOME/.var/lib/cargo"
_add_to_path post PATH "$CARGO_HOME/bin"
if command -v sccache > /dev/null; then
    export RUSTC_WRAPPER=sccache
fi

export POETRY_VIRTUALENVS_IN_PROJECT=true
export POETRY_VIRTUALENVS_PREFER_ACTIVE_PYTHON=true
export PIPENV_VENV_IN_PROJECT=1
export PIPENV_SHELL_FANCY=1

export LUA_INIT="@$DOTFILES/lua/init.lua"
export LUAROCKS_CONFIG="$DOTFILES/lua/luarocks-config.lua"
if command -v luarocks > /dev/null; then
    _add_to_path pre PATH "$(luarocks config deploy_bin_dir)"
fi

export CCACHE_DIR="$XDG_CACHE_HOME/ccache"
export CCACHE_COMPRESS=1
export CCACHE_HASHDIR=1

export SDKMAN_DIR="$XDG_DATA_HOME/sdkman"

export GITHUB_USER=majutsushi

export DVDCSS_CACHE="$XDG_CACHE_HOME/dvdcss"
export GTK_OVERLAY_SCROLLING=0
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export NO_AT_BRIDGE=1
export GRAMPSHOME="$XDG_DATA_HOME"
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

export IDEA_PROPERTIES="$DOTFILES/idea/idea.properties"
export IDEA_VM_OPTIONS="$DOTFILES/idea/idea64.vmoptions"

# https://cran.r-project.org/web/packages/startup/vignettes/startup-intro.html
export R_PROFILE_USER="$DOTFILES/R/Rprofile"


# Make sure this is first in PATH
_add_to_path pre PATH "$HOME/bin"

unset -f _add_to_path _source

# shellcheck disable=SC1072
# vim: ft=sh
