#!/bin/bash

command -v mu >/dev/null 2>&1 || exit 0

# Set up an array with outboxes
# sentboxes=( "~/Maildir/cur" "~/Maildir/.Archive" "~/Maildir/.Sent" )
sentboxes=( "~/Maildir/.Sent" )

# Run mu on each of them
for dir in "${sentboxes[@]}"; do
    mu index --maildir="${dir}" --muhome=~/.mu-sent-index --quiet
done
