#!/bin/bash

command -v mu >/dev/null 2>&1 || exit 0

INDEX_DIR="$HOME/.cache/mu-sent-index"

if ! [[ -d $INDEX_DIR ]]; then
    mu init --maildir="~/Maildir/.Sent" --muhome="$INDEX_DIR"
fi

mu index --muhome="$INDEX_DIR" --quiet
