#!/bin/bash

command -v ctags &>/dev/null || exit 0

TAGDIR=$HOME/.var/lib/tags

rm -rf "$TAGDIR"
mkdir -p "$TAGDIR"

ctags --recurse --excmd=number -f $TAGDIR/systags --extra=+q /usr/include 2> /dev/null

for dir in /usr/lib/python*; do
    base=$(basename $dir)
    ctags --recurse --excmd=number -f $TAGDIR/${base}tags $dir 2> /dev/null
done
