#!/bin/bash

declare -A filemaps

filemaps[text/x-c]=c
filemaps[text/x-perl]=perl
filemaps[text/x-python]=python
filemaps[text/x-shellscript]=sh
filemaps[text/x-diff]=diff
filemaps[application/xml]=xml

have() {
    type -P "$1" > /dev/null
}

PYG="pygmentize -f terminal256 -O style=desert"

(
    case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
        *.jar)
            have deepjarlist && deepjarlist "$1" && exit 0;;&
        *.jar|*.war|*.ear|*.xpi|*.zip)
            unzip -l "$1"
            ;;
        *.doc)
            have antiword && antiword "$1" && exit 0
            have catdoc && catdoc "$1" && exit 0
            exit 1
            ;;
        *.docx)
            have docx2txt.pl && docx2txt.pl "$1" - && exit 0
            exit 1
            ;;
        *.tar.bz2|*.tbz|*.tbz2)
            tar tjvf "$1" --force-local
            ;;
        *.tar.gz|*.tgz|*.tar.z|*.tar.dz)
            tar tzvf "$1" --force-local
            ;;
        *.gz|*.z|*.dz)
            gzip -dc "$1"
            ;;
        *)
            $PYG "$1" 2>/dev/null && exit 0

            # Use a whitelist instead of pygmentize's '-g' option to avoid too
            # many false positives
            MIMETYPE=$(file --mime-type -b $(readlink -f "$1"))
            if [[ "${filemaps[$MIMETYPE]}" != "" ]]; then
                $PYG -l ${filemaps[$MIMETYPE]} "$1"
            else
                exit 1
            fi
    esac
) 2>/dev/null
