#!/usr/bin/env bash

have() {
    type -P "$1" > /dev/null
}

hl() {
    bat --color always --style changes,numbers "$@"
}

(
    case $(echo "$1" | tr '[:upper:]' '[:lower:]') in
        *.pcap|*.pcapng|*.pcap.gz|*.pcapng.gz)
            have tshark && tshark -t a -r "$1" && exit 0;;
        *.jar)
            have deepjarlist && deepjarlist "$1" && exit 0;;&
        *.jar|*.war|*.ear|*.xpi|*.zip|*.cbz)
            unzip -l "$1"
            ;;
        *.doc)
            have antiword && antiword "$1" && exit 0
            have catdoc && catdoc "$1" && exit 0
            exit 1
            ;;
        *.docx)
            have docx2txt.pl && docx2txt.pl "$1" - && exit 0
            exit 1
            ;;
        *.scen)
            have print-scenario && print-scenario --colour "$1" && exit 0
            exit 1
            ;;
        *.tar.bz2|*.tbz|*.tbz2)
            tar tjvf "$1" --force-local
            ;;
        *.tar.gz|*.tgz|*.tar.z|*.tar.dz)
            tar tzvf "$1" --force-local
            ;;
        *.tar.xz|*.tar.lzma|*.txz)
            tar tJvf "$1" --force-local
            ;;
        *.tar)
            tar tvf "$1" --force-local
            ;;
        *.gz|*.z|*.dz)
            gzip -dc "$1"
            ;;
        *.7z)
            have 7z && 7z l "$1" && exit 0
            exit 1
            ;;
        *.rar|*.cbr)
            have unrar && unrar l "$1" && exit 0
            exit 1
            ;;
        *.class)
            hl -l java <(javap -sysinfo -private -constants "$1")
            ;;
        *.iso)
            have isoinfo && isoinfo -l -i "$1" && exit 0
            exit 1
            ;;
        *)
            hl "$1" 2>/dev/null && exit 0
            exit 1
    esac
) 2>/dev/null
