variables:
  locales: |-
    de_DE.UTF-8 UTF-8
    en_DK.UTF-8 UTF-8
    en_NZ.UTF-8 UTF-8
    en_US.UTF-8 UTF-8
    ja_JP.UTF-8 UTF-8
actions:
  packages: |
    apt-get install \
      autorandr \
      awesome \
      bat \
      bibata-cursor-theme \
      bitwise \
      cliphist \
      dex \
      fd-find \
      fuzzel \
      fzf \
      gammastep \
      grimshot \
      gron \
      hexyl \
      inputplug \
      keynav \
      libgirepository1.0-dev \
      light \
      libnotify-bin \
      mate-polkit \
      moreutils \
      playerctl \
      ripgrep \
      rofi \
      sway \
      sway-notification-center \
      swayidle \
      swaylock \
      swaysome \
      udiskie \
      vivid \
      waybar \
      wl-clipboard \
      wl-mirror \
      wlogout \
      wmctrl \
      xclip \
      xinput \
      xsecurelock \
      xsettingsd \
      xss-lock
  locale_gen: |
    echo "{{@@ locales @@}}" | while read -r LOCALE; do
      sed -Ei "s/#\\s*$LOCALE/$LOCALE/" /etc/locale.gen
    done
    locale-gen
  tzupdate: |
    curl -s -o /usr/local/bin/tzupdate https://raw.githubusercontent.com/cdown/tzupdate/develop/tzupdate.py
    chmod 755 /usr/local/bin/tzupdate
    sed -i -E -e 's,^#!/usr/bin/env python$,#!/usr/bin/env python3,' /usr/local/bin/tzupdate
    cp {{@@ _dotdrop_dotpath @@}}/tzupdate/99-tzupdate /etc/NetworkManager/dispatcher.d/
    mkdir -p /etc/sudoers.d/
    cp {{@@ _dotdrop_dotpath @@}}/tzupdate/tzupdate /etc/sudoers.d/
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles-root
  force_chmod: true
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_aptitude:
    src: aptitude/config
    dst: /root/.aptitude/config
  f_sudoers_local:
    src: sudoers.local
    dst: /etc/sudoers.d/local
    chmod: 440
  f_sway_run:
    src: sway-run
    dst: /usr/local/bin/sway-run
  f_sway_run_desktop:
    src: sway-run.desktop
    dst: /usr/local/share/wayland-sessions/sway-run.desktop
profiles:
  default:
    dotfiles:
      - ALL
    actions:
      - packages
      - locale_gen
      - tzupdate
