variables:
  locales: |-
    de_DE.UTF-8 UTF-8
    en_GB.UTF-8 UTF-8
    en_NZ.UTF-8 UTF-8
    en_US.UTF-8 UTF-8
    ja_JP.UTF-8 UTF-8
actions:
  packages: |
    apt-get install \
      autorandr \
      awesome \
      bat \
      dex \
      fd-find \
      fzf \
      gron \
      inputplug \
      keynav \
      light \
      libnotify-bin \
      moreutils \
      playerctl \
      ripgrep \
      rofi \
      wmctrl \
      xclip \
      xinput \
      xsecurelock \
      xsettingsd \
      xss-lock
  locale_gen: |
    echo "{{@@ locales @@}}" | while read -r LOCALE; do
      sed -Ei "s/#\\s*$LOCALE/$LOCALE/" /etc/locale.gen
    done
    locale-gen
config:
  backup: true
  banner: false
  create: true
  dotpath: dotfiles-root
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_aptitude:
    src: aptitude/config
    dst: /root/.aptitude/config
profiles:
  default:
    dotfiles:
      - ALL
    actions:
      - packages
      - locale_gen
