#!/bin/zsh
#
# func/baseconv
#
# zsh-based conversion between numeric bases
#
# Copyright © 1994–2008 martin f. krafft <madduck@madduck.net>
# Released under the terms of the Artistic Licence 2.0
#
# Source repository: git://git.madduck.net/etc/zsh.git
#

if [ $# -ne 3 ]; then
  echo Usage: ${0##*/} ibase obase number
  return 1
fi

typeset -li $2 var
eval ((var=${1}#${3}))
echo ${var#*\#}
