#!/usr/bin/env zsh
# ------------------------------------------------------------------------------------------
# Description
#   ZLE widget that turns dots into "../".
#
# Usage
#   Bind it to ".":
#     autoload rationalize-dots
#     zle -N rationalize-dots
#     bindkey . rationalize-dots
#     bindkey -M isearch . self-insert
# ------------------------------------------------------------------------------------------

case $LBUFFER in
    (./..|* ./..) LBUFFER+='.' ;;  # In Go: "go list ./..."
    (..|*[ /=]..) LBUFFER+='/..' ;;
    (*) LBUFFER+='.' ;;
esac

have _zsh_highlight && _zsh_highlight

if [[ "$LBUFFER" =~ "/\.\.$" ]]; then
    typeset -a line
    line=(${(z)LBUFFER})
    local dots=$line[$#line]

    zle -M ${(D)dots:a}
fi
