if exists('&macatsui')
    set nomacatsui
endif

if has('macunix')
    set guifont=Monaco:h10
else
    set guifont=DejaVu\ Sans\ Mono\ 8
endif

set guioptions+=c " use console dialogs
set guioptions-=a " don't auto-copy selection to * register
set guioptions-=e " don't use gui tabs
set guioptions-=m " don't show menubar
set guioptions-=T " don't show toolbar

" disable scrollbars
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

" "no", "yes" or "menu"; how to use the ALT key
set winaltkeys=no

set lines=50
set columns=80

" change font size with c-up/down
nnoremap <silent> <C-Up>   :let &guifont = substitute(&guifont, ' \zs\d\+', '\=eval(submatch(0)+1)', '')<CR>:set guifont?<CR>
nnoremap <silent> <C-Down> :let &guifont = substitute(&guifont, ' \zs\d\+', '\=eval(submatch(0)-1)', '')<CR>:set guifont?<CR>
