#!/bin/bash
# https://man.sr.ht/~kennylevinsen/greetd/#how-to-set-xdg_session_typewayland

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

# https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/1873
export WLR_DRM_NO_MODIFIERS=1

# https://github.com/zed-industries/zed/issues/32792
# https://github.com/swaywm/sway/issues/8755
export WLR_RENDER_NO_EXPLICIT_SYNC=1

# Prevent spamming "Atomic commit failed: Device or resource busy" logs
# https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3507
# https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md
export WLR_DRM_NO_ATOMIC=1

if [[ -f "$HOME/.profile" ]]; then
    . "$HOME/.profile"
fi

eval "$(ssh-agent -s)"

# exec sway "$@"
exec systemd-cat --identifier=sway sway "$@"

#
# If you use systemd and want sway output to go to the journal, use this
# instead of the `exec sway "$@"` above:
#
#    exec systemd-cat --identifier=sway sway "$@"
#
