#!/bin/bash
# https://man.sr.ht/~kennylevinsen/greetd/#how-to-set-xdg_session_typewayland

# Session
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway

# Wayland stuff
export MOZ_ENABLE_WAYLAND=1
export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1
export ELECTRON_OZONE_PLATFORM_HINT=auto

# Prevent spamming "Atomic commit failed: Device or resource busy" logs
# https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3507
# https://gitlab.freedesktop.org/wlroots/wlroots/-/blob/master/docs/env_vars.md
export WLR_DRM_NO_ATOMIC=1

if [[ -f "$HOME/.profile" ]]; then
    . "$HOME/.profile"
fi

eval "$(ssh-agent -s)"

# exec sway "$@"
exec systemd-cat --identifier=sway sway "$@"
