#!/usr/bin/env python

import os

rc = os.environ["HOME"] + "/.etc/mutt/attachsaverc"
hook = "message-hook '{}' 'macro attach s <save-entry><kill-line>{}<enter>y<enter>'"

with open(rc) as f:
    for line in f.readlines():
        pattern, dir = line.split("=")
        print hook.format(pattern, "~/" + dir.rstrip())
