#!/bin/bash
# Remove local branches whose upstream branch has been removed by
# "git fetch --prune" and that have been fully merged

PS4="$BASH_SOURCE:"'+\t '

[[ "${TRACE:-0}" == "1" ]] && set -x


# Only run on branch checkouts
[[ "$3" == 1 ]] || exit 0

# Macs have an old version on xargs without the flag used below.
# Most mac users will probably have Homebrew installed though
# and can easily install GNU xargs using 'brew install findutils'
gnuxargs() {
    if command -v gxargs 2>&1 > /dev/null; then
        gxargs "$@"
    else
        xargs "$@"
    fi
}

git branch -r | \
    awk '{print $1}' | \
    egrep -v -f /dev/stdin <(git branch -vv | grep ': gone\]') | \
    awk '{print $1}' | \
    gnuxargs  --no-run-if-empty git branch -d || :
