lines 60
columns 140
edge center-sized
background_opacity 1

kitty_override window_border_width=2pt
kitty_override active_border_color=#39ADB5
kitty_override draw_window_borders_for_single_window=yes
kitty_override single_window_margin_width=2
