#!/bin/bash
# https://github.com/vincentbernat/awesome-configuration/blob/master/xsession

# . $HOME/.xsessionrc

# Redirect output to the syslog instead of ~/.xsession-errors
# Close stdout and stderr first so all references to the file are gone
exec 1>&- 2>&-
exec 1> >(logger -e -t xsession -p user.info    &>/dev/null) \
     2> >(logger -e -t xsession -p user.warning &>/dev/null)
logger -e -t xsession -p user.info -f "$HOME/.xsession-errors"
rm -f "$HOME"/.xsession-errors{,.old}

eval "$(gnome-keyring-daemon --start --components=secrets)"
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &

xset s 600 120
xset dpms 0 0 1200
xss-lock --notifier="$HOME/.etc/bin/xss-notify" -- slock &

nm-applet &
pasystray &
clipit &
blueman-applet &
# /usr/lib/geoclue-2.0/demos/agent &
# redshift-gtk & # managed by systemd
compton -b
[[ -x "$HOME/src/xbanish/xbanish" ]] && "$HOME/src/xbanish/xbanish" &

xdg-user-dirs-update
xdg-user-dirs-gtk-update

# copied from /etc/X11/Xsession.d/95dbus_update-activation-env
(
     # unset login-session-specifics
     unset XDG_SEAT
     unset XDG_SESSION_ID
     unset XDG_VTNR

     dbus-update-activation-environment --verbose --systemd --all
)

# https://www.mail-archive.com/systemd-devel@lists.freedesktop.org/msg17273.html
# systemctl --user start lightson@"$DISPLAY".service

"$HOME/.etc/xorg/xsettingsd-setup"
inputplug -0 -c "$HOME/.etc/xorg/inputplug-hook"

exec awesome
