#!/bin/bash

#
# Set default Windowmanager
#
if test -z "$WINDOWMANAGER"; then
    #WINDOWMANAGER=enlightenment
    #WINDOWMANAGER="deskmenu --quit"
    WINDOWMANAGER=awesome
    #WINDOWMANAGER=fluxbox
fi

xrandr --output LVDS1 --set "scaling mode" "Full aspect"

#. $HOME/.bashrc

# =--> Set Xft DPI to match my X settings
#      when set here, xsm seems to handle the dpi better
#
#echo "Xft.dpi: 84" | xrdb -merge -

# =--> Use nice Xcursor themes
#
#echo "Xcursor.theme: redglass" | xrdb -merge -
#echo "Xcursor.size: 20" | xrdb -merge -

# Pointer appearance
#   - xcb does not support Xcursor yet
/usr/bin/xsetroot -cursor_name left_ptr

feh --bg-fill $HOME/media/desk/wallpaper/patterns/mypattern_1280x800.png

#export JAVA_HOME=/opt/java
#export PATH=$PATH:$HOME/bin:$JAVA_HOME/bin
#export LIBDIRPATH=$HOME/.lib
#export GTK_IM_MODULE="scim"

#
# start some stuff
#
#xmodmap -e "pointer = 1 2 6 4 5 8 9 3 7 10 11"
#xset s off
#xset -dpms
#kinput2 -canna &
#export XIM_PROGRAM="scim -d"
#export XMODIFIERS=@im=SCIM
#xrdb -merge .Xresources
#imwheel -b 006700
#test -f /#avfs-on

inputplug -c $HOME/.etc/xorg/xinput/inputplug-hook
$HOME/.etc/xorg/xinput/set-keyboard

# localectl set-x11-keymap us pc105 "" "ctrl:nocaps,terminate:ctrl_alt_bksp"

## test for an existing bus daemon, just to be safe
if test -z "$DBUS_SESSION_BUS_ADDRESS" ; then
    ## if not found, launch a new one
    eval `dbus-launch --sh-syntax --exit-with-session`
    echo "D-Bus per-session daemon address is: $DBUS_SESSION_BUS_ADDRESS"
fi

gnome-settings-daemon &
gnome-power-manager &
/usr/lib/gnome-volume-manager/gnome-volume-manager --sm-disable &
/usr/lib/gnome-disk-utility/gdu-notification-daemon &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
gnome-keyring-daemon --start --components=pkcs11 &
gnome-keyring-daemon --start --components=secrets &
gnome-keyring-daemon --start --components=ssh &
#/usr/lib/evolution/2.30/evolution-alarm-notify &
gnome-screensaver &

/usr/lib/cdemu-daemon/cdemu-daemon.session &
gpomme &
smart-notifier &
xcompmgr -n &
# kupfer --no-splash &

#gnome-volume-control-applet &
#alarm-clock-applet &
bluetooth-applet &
kerneloops-applet &
parcellite &
wicd-gtk &
system-config-printer-applet &

/home/jan/bin/touchpad.sh &
#xdg-user-dirs-gtk-update

# xsettingsd
# https://www.mail-archive.com/systemd-devel@lists.freedesktop.org/msg17272.html
# systemctl --user import-environment DISPLAY XAUTHORITY
# https://www.mail-archive.com/systemd-devel@lists.freedesktop.org/msg17273.html
# systemctl --user start lightson@$DISPLAY.service

# lxsession
# https://github.com/jceb/dex
# redshift
# btsync

# https://github.com/vincentbernat/awesome-configuration/blob/master/xsession
# inputplug

# xinput --set-prop 9 "Device Accel Constant Deceleration" 1
# xinput --set-prop 9 "Device Accel Velocity Scaling" 5

#
# finally start the window manager
#
exec $WINDOWMANAGER

# call failsafe
exit 0
