#!/bin/bash

readonly EVENT_TYPE="$1"
readonly DEVICE_ID="$2"
readonly DEVICE_TYPE="$3"
readonly DEVICE_NAME="$4"

readonly SCRIPTDIR="$(cd "$(dirname "$0")" && pwd -P)"

exec &> >(logger -t inputplug-hook -p user.info)

[[ "$EVENT_TYPE" == XIDeviceEnabled ]] || exit 0

case "$DEVICE_TYPE" in
    XISlaveKeyboard)
        echo "Handling keyboard '$DEVICE_NAME'"
        echo "Setting custom keymap and symbols"
        # http://madduck.net/docs/extending-xkb/
        xkbcomp -w3 "-I${XDG_CONFIG_HOME}/xkb" "${XDG_CONFIG_HOME}/xkb/keymap/default" "${DISPLAY%%.*}"
        ;;
    XISlavePointer)
        echo "Handling pointer '$DEVICE_NAME'"
        case "$DEVICE_NAME" in
            Microsoft\ Microsoft\ Trackball\ Explorer®)
                echo "Remapping trackball buttons"
                xinput --set-button-map "$DEVICE_ID" 1 2 8 4 5 6 7 3 9 10 11 12 13
                ;;
            Microsoft\ \ Microsoft\ Basic\ Optical\ Mouse\ v2.0\ )
                if [[ $(hostname) == vanadis ]]; then
                    echo "Enabling left-hand mode on mouse"
                    xinput set-prop "$DEVICE_ID" "libinput Left Handed Enabled" 1
                fi
                ;;
        esac
        ;;
esac

if [[ -f "$HOME/.local/etc/inputplug" ]]; then
    . "$HOME/.local/etc/inputplug"
fi
