#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
else
    # Initial commit: diff against an empty tree object
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# If there are whitespace errors, print the offending file names and fail.
exec git -c core.whitespace=blank-at-eol,space-before-tab,tab-in-indent,blank-at-eof,cr-at-eol diff-index --check --cached $against --
