#!/does/not/exist/but/fools/vim's/syntax/highlighting/perl
# Htag.pl 0.0.18 - config file
# This file is parsed as Perl by perl.
#
# My defaults when all else has failed.

# All tagfiles but "fluffybunnies"
# See comments about tagmatch/tagdir/tagfile in sample.htrc

undef $cfg{'tagfile'};
undef $cfg{'tagfiles'};
$cfg{'tagmatch'} = '^/home/jan/\.htagrc/tags/default$';
$cfg{'tagdir'} = "~/.htagrc/tags";

# No fortunes (remove vars just through paranoia really since they aren't
# defined in .htrc but they could be if someone doesn't have a separate
# default config but uses .htrc as the default)
undef $cfg{'fortune'};
undef $cfg{'fortuneval'};
undef $cfg{'fortuneargs'};

# All sigs in ~/.sigs that start with bc- or blackcat
# See comments about sigs/sigmatch/sigdir in sample.htrc

undef $cfg{'sigs'};
undef $cfg{'sigmatch'};
$cfg{'sigdir'} = "~/.htagrc/sigs";
$cfg{'sigmatch'} = '^/home/jan/\.htagrc/sigs/default$';

1;

