#!/bin/bash

SOURCEWIN="$1"

NUMSESSIONS=$(tmux list-sessions | wc -l)

echo 'local awful = require("awful") awful.util.spawn("x-terminal-emulator")' | awesome-client

while (( $(tmux list-sessions | wc -l) == NUMSESSIONS )); do
    sleep 0.1
done

NEWSESSION=$(tmux list-sessions -F '#{session_created} #{session_name}' | sort -n | tail -1 | awk '{ printf $2 }')

tmux move-window -s "${SOURCEWIN}" -t ${NEWSESSION}:
tmux kill-window -t ${NEWSESSION}:1
tmux move-window -r
tmux move-window -r -t ${NEWSESSION}:
