#!/bin/bash
# Like 'tmux select-pane', but if Vim is running in the current pane it sends
# a '<M-h/j/k/l>' keystroke to Vim instead.
set -e

cmd="$(tmux display -p '#{pane_title}')"

if [[ "${cmd}" == vim* ]]; then
    direction="$(echo "${1#-}" | tr 'lLDUR' 'phjkl')"
    # forward the keystroke to Vim
    tmux send-keys "M-$direction"
else
    tmux select-pane "$@"
fi
