#!/usr/bin/perl
# Originally from
# http://artisan.karma-lab.net/creer-plugin-urxvt-sauvegarder-vim-automatiquement
# with small changes

sub on_start {
    my ($term) = @_;
    $term->{focus_activated} = 0;
}

sub on_osc_seq_perl {
    my ($term, $osc, $resp) = @_;
    return unless $osc =~ s/^focus;//;
    $term->{focus_activated} = $osc eq 'on' ? 1 : 0;
}

sub on_focus_in {
    my ($term) = @_;

    if ($term->{focus_activated}) {
        $term->tt_write("\033[I");
    }
}

sub on_focus_out {
    my ($term) = @_;

    if ($term->{focus_activated}) {
        $term->tt_write("\033[O");
    }
}
