#!/bin/bash

EVENT_TYPE="$1"
DEVICE_ID="$2"
DEVICE_TYPE="$3"
DEVICE_NAME="$4"

SCRIPTDIR="$(cd $(dirname "$0") && pwd -P)"

if [[ "$EVENT_TYPE" == "XIDeviceEnabled" ]] && \
        [[ "$DEVICE_TYPE" == "XISlaveKeyboard" ]]; then
    logger -t inputplug-hook "Setting custom keymap and symbols"
    "$SCRIPTDIR/set-keyboard"
fi
