set nocompatible

if exists(":filetype")
    filetype plugin indent on
endif

if has("syntax")
    syntax on
endif

set autoread
set backspace=indent,eol,start
set clipboard=unnamed,unnamedplus,exclude:cons\|linux
set completeopt=longest,menuone
set confirm
set cursorline
set display=lastline
set hlsearch
set hidden
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=tab:._,trail:.,nbsp:x,precedes:<,extends:>
set more
set nrformats-=octal
" set number
set ruler
set smartcase
set scrolloff=5
set shortmess=aoOtI
set showcmd
set showmode
set sidescrolloff=5
set virtualedit=all
set wrap

set formatoptions+=r " continue comments when pressing <Enter>
set formatoptions-=o " don't continue comments when pressing o/O
set formatoptions+=n " recognize numbered lists when formatting
set formatoptions+=2 " use indent of second line in paragraph
set formatoptions+=l " don't break long lines that were already too long
if v:version > 703 || v:version == 703 && has("patch541")
    set formatoptions+=j " Delete comment character when joining commented lines
endif

set tabstop=8
set shiftwidth=4
set smarttab
set expandtab
set autoindent

set timeout
set nottimeout
set timeoutlen=1000
set ttimeoutlen=10

set wildmode=list:longest,full
if exists("&wildignorecase")
    set wildignorecase
endif

if !exists('g:loaded_matchit') && findfile('plugin/matchit.vim', &rtp) ==# ''
    runtime! macros/matchit.vim
endif

highlight Search ctermbg=15 ctermfg=0

nnoremap <silent> <C-l> :nohlsearch<CR><C-l>
nnoremap <silent> g/ :execute 'vimgrep /' . @/ . '/g %'<CR>:copen<CR>
