set nocompatible

if exists(":filetype")
    filetype plugin indent on
endif

if has("syntax")
    syntax on
endif

set autoread
set backspace=indent,eol,start
set completeopt=longest,menuone
set confirm
set display=lastline
set hlsearch
set hidden
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=tab:._,trail:.,nbsp:x,precedes:<,extends:>
set more
" set number
set ruler
set smartcase
set scrolloff=5
set shortmess=aoOtI
set showcmd
set showmode
set virtualedit=all
set wrap

set formatoptions+=r " continue comments when pressing <Enter>
set formatoptions-=o " don't continue comments when pressing o/O
set formatoptions+=n " recognize numbered lists when formatting
set formatoptions+=2 " use indent of second line in paragraph
set formatoptions+=l " don't break long lines that were already too long

set tabstop=8
set shiftwidth=4
set smarttab
set expandtab
set autoindent

set timeout
set nottimeout
set timeoutlen=1000
set ttimeoutlen=10

set wildmode=list:longest,full
if exists("&wildignorecase")
    set wildignorecase
endif
